/**
 * Builds design/prototype/data.js for the design prototype.
 * IN and US come from the published v3 releases in data/; the other five banks come from official series fetched on
 * 7 Oct 2026 (change points only) until their adapters land in Phase 3.
 * Usage: node design/prototype/build-data.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import type { CountryRelease, Level } from '../../schema/release.ts';
import type { Manifest, ScheduleFile } from '../../schema/files.ts';
import { fetchText } from '../../pipeline/lib/http.ts';
import { parseMpcResolution } from '../../pipeline/countries/in/resolution.ts';

const ROOT = new URL('../../', import.meta.url);
const read = <T>(path: string): T => JSON.parse(readFileSync(new URL(path, ROOT), 'utf8')) as T;
const lohi = (l: Level): [number, number] => (l.kind === 'range' ? [l.lowBps, l.highBps] : l.kind === 'point' ? [l.bps, l.bps] : [NaN, NaN]);

const manifest = read<Manifest>('data/manifest.json');
const schedule = read<ScheduleFile>('data/schedule.json');
const now = '2026-10-07T12:00:00Z';

async function fromRelease(cc: 'IN' | 'US') {
  const r = read<CountryRelease>(`data/${manifest.countries[cc].path}`);
  const excerpts = new Map<string, string>();
  for (const d of r.decisions.filter(x => !x.excerpt && x.statementUrl && x.announcedAt >= '2026-01-01')) {
    const page = await fetchText(d.statementUrl!);
    excerpts.set(d.id, parseMpcResolution(page.body, d.statementUrl!).excerpt);
  }
  const policyFrom = r.eras.find(e => e.basis === 'policy')!.from;
  return {
    cc, release: r.release.hash.slice(0, 12), policyFrom,
    eras: r.eras.map(e => ({ from: e.from, to: e.to, basis: e.basis, label: e.instrument, note: e.note })),
    series: r.series.map(p => [p.date, ...lohi(p.level), p.evidence === 'official' ? 1 : 0]),
    decisions: r.decisions.map(d => ({
      date: d.announcedAt.slice(0, 10), effective: d.effectiveDate, lo: lohi(d.level)[0], hi: lohi(d.level)[1], change: d.changeBps,
      dir: d.direction, vote: d.vote, stance: d.stance, excerpt: d.excerpt ?? excerpts.get(d.id) ?? null, url: d.statementUrl, offCycle: d.offCycle,
    })),
    next: schedule.items.filter(i => i.cc === cc && !i.resolved && i.announceAt > now).slice(0, 2).map(i => i.announceAt),
    transmission: r.transmission,
    sources: r.sources.length,
  };
}

const official = read<Record<string, [string, number | [number, number]][]>>('design/prototype/source/official-series-2026-10-07.json');
function fromSeries(cc: string) {
  const series = official[cc].map(([date, v]) => (Array.isArray(v) ? [date, v[0], v[1], 1] : [date, v, v, 1]));
  return { cc, release: null, policyFrom: series[0][0], eras: [], series, decisions: [], next: [], transmission: [], sources: 1 };
}

const countries = {
  IN: await fromRelease('IN'),
  US: await fromRelease('US'),
  EA: fromSeries('EA'), GB: fromSeries('GB'), CA: fromSeries('CA'), AU: fromSeries('AU'), BR: fromSeries('BR'),
};
writeFileSync(new URL('design/prototype/data.js', ROOT), `// Generated by design/prototype/build-data.ts on ${now.slice(0, 10)}. Do not edit.\nwindow.ATLAS_DATA = ${JSON.stringify({ generatedAt: now, countries })};\n`);
console.log('data.js written:', Object.keys(countries).join(', '));
